# Generated by Django 5.0.7 on 2024-07-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_buyer', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
