# Generated by Django 5.0.7 on 2024-07-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
